### ISSUE TITLE
pin github version

### ISSUE THREAD

**Issue by gr2m** [freaktechnik/github-stub#5]
Hey Martin,

this library is pretty cool, thanks!

As the maintainer of `github`, just a heads up. You currently have a version range set in package.json
https://github.com/freaktechnik/github-stub/blob/c73a9c41cef6d38897dcd91a26ee8047986f4931/package.json#L27

The `github/lib/routes.json` path is not part of the public API so it can change at any time. Greenkeeper should warn you ones github breaks, but to avoid users of your library to have broken tests all of the sudden I suggest that you pin the version number to just `"12.0.0"`. Greenkeeper will then send you a PR for every version

**Comment by freaktechnik** [comment]
As I understand the package-lock should also do that, however it's better to be save. Thanks for the suggestion!

**Comment by gr2m** [comment]
`package-lock.json` is only used for your local dev setup, it is not published to the npm registry, so consumers of your library will still get the last version that matches your defined version range
